FROM ubuntu:24.04

RUN apt update && apt install -y \
  curl gcc g++ openjdk-17-jdk \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/sandbox

RUN architecture=$(dpkg --print-architecture) && if [ "$architecture" = "arm64" ]; then \
  curl -L "https://github.com/skkuding/Judger/releases/download/v1.0.0-alpha/libjudger-arm64.a" -o "/app/sandbox/libjudger.so"; \
  else \
  curl -L "https://github.com/skkuding/Judger/releases/download/v1.0.0-alpha/libjudger-amd64.a" -o "/app/sandbox/libjudger.so"; \
  fi

COPY ./entrypoint.sh .
ENTRYPOINT ["./entrypoint.sh"]
CMD ["/bin/bash"]